title: 'Orgullo 2016'
author:
  name: XEGA
  email: info@xega.org
  url: 'https://xega.org/'
  gravatar: info@xega.org
  description: 'Programación Orgullo LGTB+ Asturias'
  route: ''
taxonomies:
  - tag
metadata:
  description: ''
summary:
  enabled: true
  format: short
  size: 100
  delimiter: '==='
  striptags: true
blog:
  route: /blog
description: 'WebApp con la programación del Orgullo LGTB+ de Asturias'
global_featured_image: featured.jpg
social:
  -
    text: facebook
    url: //www.facebook.com/xega.ast
  -
    text: twitter
    url: //twitter.com/xega
  -
    text: google-plus
    url: //plus.google.com/+XegaOrg
  -
    text: linkedin
    url: //www.linkedin.com/company/xega
  -
    text: home
    url: //xega.org
menu:
  -
    url: https://apps.xega.org/orgullo/2015/
    text: 'Orgullo 2015'
slider:
  - image: header.jpg
    title: "Manifestación «Orgullo Asturias»"
    url: https://apps.xega.org/orgullo/2016/es/manifestacion-orgullo-lgtb-asturias.html
  - image: 20160618000000-0001b-banner_cabecera_web_festival_cine_lgbtiq-niemeyer-spa.png
    title: "Festival de cine LGBTIQ"
    url: https://apps.xega.org/orgullo/2016/es/festival-cine-lgbtiq-niemeyer.html
  - image: banner_orgullin_2016.jpg
    title: "VI Orgullín del Norte"
    url: https://apps.xega.org/orgullo/2016/es/vi-orgullin-norte.html
  - image: 2015-oviedo-00-grande.jpg
    title: "Acto político-institucional «28 de junio»"
    url: https://apps.xega.org/orgullo/2016/es/acto-politico-institucional-28-junio.html
  - image: xega-bus.jpg
    title: "Autobús de XEGA a la Manifestación de Madrid"
    url: https://apps.xega.org/orgullo/2016/es/autobus-manifestacion-orgullo-madrid.html
  - image: 20160702183000-0002a--banner_manifestacion_orgullo_madrid-felgtb-spa.jpg
    title: "Manifestación «Orgullo LGTB 2016» en Madrid"
    url: https://apps.xega.org/orgullo/2016/es/manifestacion-orgullo-lgtb-madrid.html
    
copyright: 'MADE WITH GRAV AND <span class="fa fa-heart" style="color:#f00"></span> IN ASTURIES'
