title: Prueba
default_lang: es
author:
  name: XEGA
  email: webmaster@xega.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Es posible que alguna vez se te haya pasado por la cabeza hacerte la prueba del VIH, el virus que causa el sida. Es un asunto importante. Tal vez no sepas qué ventajas tiene hacérsela, puede que sientas miedo o angustia al pensar en ello, incluso puede que no sepas dónde hacerla.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
