title: 'Sexo + seguro'
author:
  name: XEGA
  email: info@xega.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Esta guía está pensada para gais y hombres bisexuales que viven con el V.'
